import type { Metadata } from "next";
import Cabecalho from "@/components/Cabecalho/Cabecalho";
import Rodape from "@/components/Rodape/Rodape";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Cabecalho 
        titulo={"EXEMPLO DE PROPS E TYPES"}
        msg={"Olá props!!"}
        //precisa de duas chaves pq a primeira é a props e a segunda são os atributos do objeto
        usuario={{nome:"José", email:"jose@email.com"}}
        />
        {children}
        <Rodape/>
        </body>
    </html>
  );
}


